version: '3.1'
services:
  zk_main:
    build:
      context: ./
    container_name: zk_main
    restart: always
    ports:
      - 2181
      - 2888
      - 3888
      - "8080:8080"
  zk_follower:
    build:
      context: ./
    restart: always
    ports:
      - 2181
      - 2888
      - 3888
      - 8080
    environment:
      - ZK_HOST=zk_main
